// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAPI.Data;

#nullable disable

namespace SistemaAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251206000000_AgregarCampoActivoConsecutivo")]
    partial class AgregarCampoActivoConsecutivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LibreriaModelos.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutivoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuditoriaID");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("LibreriaModelos.Consecutivo", b =>
                {
                    b.Property<int>("ConsecutivoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanceladoPor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remitente")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsecutivoID");

                    b.ToTable("Consecutivo");
                });

            modelBuilder.Entity("LibreriaModelos.Reporte", b =>
                {
                    b.Property<int>("ReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutivoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReporteID");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("LibreriaModelos.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRol")
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            RolID = 2,
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("LibreriaModelos.Sistema", b =>
                {
                    b.Property<int>("SistemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gerencia")
                        .HasColumnType("TEXT");

                    b.HasKey("SistemaID");

                    b.ToTable("Sistema");

                    b.HasData(
                        new
                        {
                            SistemaID = 1,
                            Gerencia = "ALS"
                        });
                });

            modelBuilder.Entity("LibreriaModelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            IDRol = 1,
                            NombreUsuario = "Olga Vázquez",
                            NumEmpleado = 3248,
                            Password = "pass"
                        },
                        new
                        {
                            UsuarioID = 2,
                            IDRol = 2,
                            NombreUsuario = "Usuario Comun",
                            NumEmpleado = 1001,
                            Password = "userpass"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
