// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Ord.Data;

#nullable disable

namespace Proyecto_Ord.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251106170217_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Proyecto_Ord.Models.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutivoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuditoriaID");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Proyecto_Ord.Models.Consecutivo", b =>
                {
                    b.Property<int>("ConsecutivoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanceladoPor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remitente")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsecutivoID");

                    b.ToTable("Consecutivos");
                });

            modelBuilder.Entity("Proyecto_Ord.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutivoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReporteID");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Proyecto_Ord.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRol")
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            NombreRol = "SuperAdmin"
                        },
                        new
                        {
                            RolID = 2,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            RolID = 3,
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("Proyecto_Ord.Models.Sistema", b =>
                {
                    b.Property<int>("SistemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gerencia")
                        .HasColumnType("TEXT");

                    b.HasKey("SistemaID");

                    b.ToTable("Sistema");
                });

            modelBuilder.Entity("Proyecto_Ord.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumEmpleado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            IDRol = 1,
                            NombreUsuario = "Super Admin",
                            NumEmpleado = 1001,
                            Password = "superadminpass"
                        },
                        new
                        {
                            UsuarioID = 2,
                            IDRol = 2,
                            NombreUsuario = "Admin",
                            NumEmpleado = 1002,
                            Password = "adminpass"
                        },
                        new
                        {
                            UsuarioID = 3,
                            IDRol = 3,
                            NombreUsuario = "Usuario",
                            NumEmpleado = 1003,
                            Password = "userpass"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
